- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
      tags:
        - node
        - zsh
  tasks:
    - include: ubuntu-fem-v2-tasks/fem-tasks/zsh.yml
    - include: ubuntu-fem-v2-tasks/fem-tasks/node.yml
